/**/
layout(local_size_x = 1, local_size_y = 1) in;

layout(set = 0, binding = 5, r16f) uniform readonly image2DArray kTextures2DIn[];
layout(set = 0, binding = 5, r16f) uniform writeonly image2DArray kTextures2DOut[];

layout(push_constant) uniform PushConstants
{
    uint texCurrSceneLuminance;
    uint texPrevAdaptedLuminance;
    uint texAdaptedOut;
    float adaptationSpeed;
    uint enableAdaptation;
}
pc;

void main()
{
    const ivec3 pos = ivec3(0, 0, gl_GlobalInvocationID.z);
    const int layerCount = imageSize(kTextures2DIn[pc.texCurrSceneLuminance]).z;

    float lumCurr = 0.0;
    for (int layer = 0; layer != layerCount; layer++)
    {
        const ivec3 layerPos = ivec3(0, 0, layer);
        lumCurr += imageLoad(kTextures2DIn[pc.texCurrSceneLuminance], layerPos).x;
    }
    lumCurr /= float(layerCount);

    float lumPrev = imageLoad(kTextures2DIn[pc.texPrevAdaptedLuminance], ivec3(0, 0, 0)).x;

    float factor = 1.0 - exp(-pc.adaptationSpeed);
    float newAdaptation = pc.enableAdaptation != 0 ? lumPrev + (lumCurr - lumPrev) * factor : lumCurr;

    imageStore(kTextures2DOut[pc.texAdaptedOut], pos, vec4(newAdaptation));
}
