//
layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 5, rgba16f) uniform writeonly image2DArray kTextures2DOutRGBA[];
layout(set = 0, binding = 5, r16f) uniform writeonly image2DArray kTextures2DOutR[];

layout(push_constant) uniform PushConstants
{
    uint texColor;
    uint texOut;       // rgba16f
    uint texLuminance; // r16f
    uint smpl;
    float exposure;
    uint enableBloom;
}
pc;

void main()
{
    const uvec3 gid = gl_GlobalInvocationID;
    const uint view_idx = gid.z;
    const uvec3 sizeIn = uvec3(textureBindlessSize2DArray(pc.texColor));
    const uvec3 sizeOut = uvec3(imageSize(kTextures2DOutRGBA[pc.texOut]));

    if (gid.x >= sizeOut.x || gid.y >= sizeOut.y || gid.z >= sizeOut.z || gid.x >= sizeIn.x || gid.y >= sizeIn.y ||
        gid.z >= sizeIn.z)
    {
        return;
    }

    const ivec3 outPos = ivec3(gid);
    const vec2 xy = vec2(gid.xy);
    const vec2 outSize = vec2(sizeOut.xy);
    const vec2 uv0 = xy / outSize;
    const vec2 uv1 = (xy + vec2(1)) / outSize;

    vec2 dxdy = (uv1 - uv0) / 3;

    vec4 color = vec4(0);

    // 3x3 box filter
    for (int v = 0; v != 3; v++)
    {
        for (int u = 0; u != 3; u++)
        {
            color += textureBindless2DArrayLod(pc.texColor, pc.smpl, uv0 + vec2(u, v) * dxdy, view_idx, 0.0);
        }
    }

    float luminance = pc.exposure * dot(color.rgb / 9, vec3(0.2126, 0.7152, 0.0722));

    if (pc.enableBloom != 0)
    {
        vec3 rgb = luminance > 1.0 ? color.rgb : vec3(0);
        imageStore(kTextures2DOutRGBA[pc.texOut], outPos, vec4(rgb, 1.0));
    }
    imageStore(kTextures2DOutR[pc.texLuminance], outPos, vec4(luminance));
}
