//

#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout(local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0) uniform texture2D kTextures2D[];
layout(set = 0, binding = 1) uniform sampler kSamplers[];
layout(set = 0, binding = 2, rg8) uniform writeonly image2D kTextures2DOut[];

vec4 textureBindless2D(uint textureid, uint smpl, vec2 uv)
{
    return textureLod(nonuniformEXT(sampler2D(kTextures2D[textureid], kSamplers[smpl])), uv, 0);
}

ivec2 textureBindlessSize2D(uint textureid)
{
    return textureSize(nonuniformEXT(kTextures2D[textureid]), 0);
}

layout(constant_id = 0) const bool kIsHorizontal = true;

layout(push_constant) uniform PushConstants
{
    uint texIn;
    uint texOut;
    uint texDepth;
    uint smpl;
    float depthThreshold;
}
pc;

const int kFilterSize = 5;

const float16_t gaussWeights[kFilterSize] = float16_t[](0.0625hf, 0.25hf, 0.375hf, 0.25hf, 0.0625hf);

void main()
{
    ivec2 size = textureBindlessSize2D(pc.texIn);
    ivec2 xy = ivec2(gl_GlobalInvocationID.xy);

    if (xy.x >= size.x || xy.y >= size.y)
    {
        return;
    }

    vec2 texCoord = (vec2(xy) + vec2(0.5)) / vec2(size);
    float texScaler = 1.0 / (kIsHorizontal ? float(size.x) : float(size.y));

    f16vec2 fragColor = f16vec2(textureBindless2D(pc.texIn, pc.smpl, texCoord).rg);
    float fragDepth = textureBindless2D(pc.texDepth, pc.smpl, texCoord).r;

    f16vec2 c = f16vec2(0.0hf);
    float16_t totalWeight = 0.0hf;

    for (int i = 0; i < kFilterSize; i++)
    {
        float offset = float(i - kFilterSize / 2);
        vec2 uv = texCoord + texScaler * (kIsHorizontal ? vec2(offset, 0.0) : vec2(0.0, offset));

        f16vec2 color = f16vec2(textureBindless2D(pc.texIn, pc.smpl, uv).rg);
        float depth = textureBindless2D(pc.texDepth, pc.smpl, uv).r;

        float depthDiff = abs(depth - fragDepth);
        float16_t w = gaussWeights[i] * float16_t(1.0 - clamp(depthDiff * pc.depthThreshold, 0.0, 1.0));

        c += color * w;
        totalWeight += w;
    }

    f16vec2 result = totalWeight > 0.001hf ? c / totalWeight : fragColor;
    imageStore(kTextures2DOut[pc.texOut], xy, vec4(result, 0.0hf, 1.0hf));
}
